src/Entity/TypeMenu.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TypeMenuRepository")
 */
class TypeMenu
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $published;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Menu", mappedBy="typeMenu")
     */
    private $menus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="typeMenus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    /**
     * @return Collection|Menu[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setTypeMenu($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->contains($menu)) {
            $this->menus->removeElement($menu);
            // set the owning side to null (unless already changed)
            if ($menu->getTypeMenu() === $this) {
                $menu->setTypeMenu(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function __toString () {
        return $this->name;
    }
}

src/Form/TypeMenuType.php
<?php

namespace App\Form;

use App\Entity\TypeMenu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeMenuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('image')
            ->add('updated_at')
            ->add('description')
            ->add('published')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TypeMenu::class,
        ]);
    }
}

src/Controller/TypeMenuController.php
<?php

namespace App\Controller;

use App\Entity\TypeMenu;
use App\Form\TypeMenuType;
use App\Repository\TypeMenuRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/type/menu")
 */
class TypeMenuController extends AbstractController
{
    /**
     * @Route("/", name="type_menu_index", methods={"GET"})
     */
    public function index(TypeMenuRepository $typeMenuRepository): Response
    {
        return $this->render('type_menu/index.html.twig', [
            'type_menus' => $typeMenuRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="type_menu_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $typeMenu = new TypeMenu();
        $form = $this->createForm(TypeMenuType::class, $typeMenu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($typeMenu);
            $entityManager->flush();

            return $this->redirectToRoute('type_menu_index');
        }

        return $this->render('type_menu/new.html.twig', [
            'type_menu' => $typeMenu,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="type_menu_show", methods={"GET"})
     */
    public function show(TypeMenu $typeMenu): Response
    {
        return $this->render('type_menu/show.html.twig', [
            'type_menu' => $typeMenu,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="type_menu_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TypeMenu $typeMenu): Response
    {
        $form = $this->createForm(TypeMenuType::class, $typeMenu);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('type_menu_index', [
                'id' => $typeMenu->getId(),
            ]);
        }

        return $this->render('type_menu/edit.html.twig', [
            'type_menu' => $typeMenu,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="type_menu_delete", methods={"DELETE"})
     */
    public function delete(Request $request, TypeMenu $typeMenu): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeMenu->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($typeMenu);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_menu_index');
    }
}

templates/type_menu/_delete_form.html.twig
<form method="post" action="{{ path('type_menu_delete', {'id': type_menu.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_menu.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/type_menu/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/type_menu/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TypeMenu{% endblock %}

{% block body %}
    <h1>Edit TypeMenu</h1>

    {{ include('type_menu/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('type_menu_index') }}" class="btn btn-primary">back to list</a>

    {{ include('type_menu/_delete_form.html.twig') }}
{% endblock %}

templates/type_menu/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TypeMenu index{% endblock %}

{% block body %}
    <h1>TypeMenu index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Image</th>
                <th>Updated_at</th>
                <th>Description</th>
                <th>Published</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type_menu in type_menus %}
            <tr>
                <td>{{ type_menu.id }}</td>
                <td>{{ type_menu.name }}</td>
                <td>{{ type_menu.image }}</td>
                <td>{{ type_menu.updatedAt ? type_menu.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ type_menu.description }}</td>
                <td>{{ type_menu.published ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('type_menu_show', {'id': type_menu.id}) }}" class="btn btn-primary"->show</a>
                    <a href="{{ path('type_menu_edit', {'id': type_menu.id}) }}" class="btn btn-secondary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('type_menu_new') }}" class="btn btn-success">Create new</a>
{% endblock %}

templates/type_menu/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TypeMenu{% endblock %}

{% block body %}
    <h1>Create new TypeMenu</h1>

    {{ include('type_menu/_form.html.twig') }}

    <a href="{{ path('type_menu_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/type_menu/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TypeMenu{% endblock %}

{% block body %}
    <h1>TypeMenu</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ type_menu.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ type_menu.name }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ type_menu.image }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ type_menu.updatedAt ? type_menu.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ type_menu.description }}</td>
            </tr>
            <tr>
                <th>Published</th>
                <td>{{ type_menu.published ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('type_menu_index') }}" class="btn btn-primary">back to list</a>

    <a href="{{ path('type_menu_edit', {'id': type_menu.id}) }}" class="btn btn-secondary">edit</a>

    {{ include('type_menu/_delete_form.html.twig') }}
{% endblock %}